// bindings/vue/examples/components/Carousel.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="left"><ons-toolbar-button @click="carouselIndex--">Prev: Index--</ons-toolbar-button></div>
      <div class="center">Index: {{carouselIndex}}</div>
      <div class="right"><ons-toolbar-button @click="carouselIndex++">Next: Index++</ons-toolbar-button></div>
    </v-ons-toolbar>

    <v-ons-carousel fullscreen :index="carouselIndex" @postchange="carouselIndex = $event.activeIndex" swipeable auto-scroll overscrollable @refresh="log('refresh!!')" @overscroll="log('overscroll!!')">
      <v-ons-carousel-item v-for="(value, key) in items" :key="key" :style="{backgroundColor: value}">
        <div style="text-align: center; font-size: 30px; margin-top: 20px; color: #fff;">{{key}}</div>
      </v-ons-carousel-item>
    </v-ons-carousel>
  </v-ons-page>
</template>

<script>
	export default {
    data: function() {
      return {
        carouselIndex: 1,
        items: {
          BLUE: '#085078',
          DARK: '#373B44',
          ORANGE: '#D38312'
        }
      }
    },

    methods: {
      log: function(msg) {
        console.log(msg);
      }
    }
	};
</script>

// react-onsenui-examples/src/components/Carousel.js
import React from 'react';
import MyToolbar from './MyToolbar';

import {
  Page,
  Button,
  Carousel,
  CarouselItem,
  BottomToolbar,
  ToolbarButton
} from 'react-onsenui';

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      index: 1,
      items: [
        'gray',
        'red',
        'orange',
        'blue'
      ]
    };
    this.goTo = this.goTo.bind(this);
  }

  goTo(number) {
    console.log('number', number);
    this.setState({index: number});
  }

  moveRight() {
    if (this.state.index < this.state.items.length - 1) {
      this.setState({ index: this.state.index + 1 })
    }
  }

  moveLeft() {
    if (this.state.index > 0) {
      this.setState({ index: this.state.index - 1 })
    }
  }

  render() {
    return (
      <Page renderToolbar={() => <MyToolbar title='Fullscreen' />}>
        <Carousel
          animationOptions={{
            duration: 1.0,
            delay: 0.3,
            timing: 'ease-in'
          }}
          index={this.state.index}
          onPostChange={(event) => this.setState({index: event.activeIndex})}
          onOverscroll={() => console.log('onOverscroll')}
          onRefresh={() => console.log('onRefresh')}
          swipeable overscrollable autoScroll fullscreen autoScrollRatio={0.2}>

          {this.state.items.map((item, index) =>
            <CarouselItem key={index} style={{backgroundColor: item}}>
              <div className='item-label'>{item}</div>
              {this.state.items.map((item, index) =>
                <Button key={index} onClick={() => this.goTo(index)}> Go to page {index + 1}</Button>
              )}
              <Button onClick={() => this.setState({items: this.state.items.slice(0, this.state.items.length - 1)})}>Remove</Button>
              <Button onClick={() => this.setState({items: [...this.state.items, 'yellow']})}>Add</Button>
            </CarouselItem>
          )}
        </Carousel>

        <BottomToolbar>
          <ToolbarButton style={{float: 'right'}} onClick={() => this.moveRight()}>Next</ToolbarButton>
          <ToolbarButton style={{float: 'left'}} onClick={() => this.moveLeft()}>Prev</ToolbarButton>
        </BottomToolbar>
      </Page>
    );
  }
};
