// bindings/vue/examples/components/SpeedDial.vue
<template>
  <ons-page>
    <ons-toolbar>
      <div class="center">
        Speed dial
      </div>
      <div class="left">
        <ons-back-button label="Home" @click="$pop()"></ons-back-button>
      </div>
    </ons-toolbar>

    <ons-speed-dial position="bottom right">
      <ons-fab>
        <ons-icon icon="md-share"></ons-icon>
      </ons-fab>
      <ons-speed-dial-item
        @click="$notification.confirm('Share on Twitter?')"
      >
        <ons-icon icon="md-twitter"></ons-icon>
      </ons-speed-dial-item>
      <ons-speed-dial-item
        @click="$notification.confirm('Share on Facebook?')"
      >
        <ons-icon icon="md-facebook"></ons-icon>
      </ons-speed-dial-item>
      <ons-speed-dial-item
        @click="$notification.confirm('Share on Google+?')"
      >
        <ons-icon icon="md-google-plus"></ons-icon>
      </ons-speed-dial-item>
    </ons-speed-dial>

  </ons-page>
</template>

<script>
  import {
    OnsBackButton
  } from 'vue-onsenui';

  export default {
    components: {
      OnsBackButton
    }
  };
</script>

// bindings/react/demo/examples/SpeedDial.js
import React from 'react';

import {
  Page,
  Icon,
  Fab,
  SpeedDial,
  SpeedDialItem,
  Toolbar,
  BackButton
} from 'react-onsenui';

export default class extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      modifier: 'material',
    };
  }

  renderToolbar() {
    return (
      <Toolbar>
        <div className='left'>
          <BackButton>Back</BackButton>
        </div>
        <div className='center'>
          Speed Dial
        </div>
      </Toolbar>
    );
  }

  renderFixed() {
    return (
      <SpeedDial disabled={false} direction='up' onClick={() => console.log('test1')} position='bottom right'>
        <Fab>
          <Icon
            icon='fa-twitter'
            size={26}
            fixedWidth={false}
            style={{verticalAlign: 'middle'}} />
        </Fab>
        <SpeedDialItem onClick={() => console.log('speed A')}> A </SpeedDialItem>
        <SpeedDialItem onClick={() => console.log('speed B')}> B </SpeedDialItem>
        <SpeedDialItem onClick={() => console.log('speed C')}> C </SpeedDialItem>
        <SpeedDialItem onClick={() => console.log('speed D')}> D </SpeedDialItem>
      </SpeedDial>
    );
  }

  render() {
    return (
      <Page renderFixed={this.renderFixed} renderToolbar={this.renderToolbar}>
      </Page>
    );
  }
}
