// bindings/react/demo/examples/Segment.js
import React from 'react';

import {
  Page,
  Toolbar,
  BackButton,
  Segment,
  Tabbar,
  Tab,
  Button
} from 'react-onsenui';

import MyToolbar from './MyToolbar';

class TabPage extends React.Component {
  render() {
    return (
      <Page>
        {this.props.active
          ? <h2>{this.props.title}</h2>
          : null}
        <Button onClick={this.props.logIndexes}>Log current button index</Button>
      </Page>
    );
  }
}

class HomePage extends React.Component {
  render() {
    return (
      <Page>
        {this.props.active
          ? <h2>{this.props.title}</h2>
          : null}
        <Button onClick={this.props.changeTab}>Chang tab via tabbar</Button>
        <Button onClick={this.props.changeButton}>Change tab via segment</Button>
        <Button onClick={this.props.logIndexes}>Log current button index</Button>
      </Page>
    );
  }
}

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      segmentIndex: 0,
      tabbarIndex: 0
    };
    this.renderTabs = this.renderTabs.bind(this);
  }

  renderTabs(activeIndex, tabbar) {
    return [
      {
        content: <HomePage key="page1" changeTab={() => { this.setState({ tabbarIndex: 1 }); }}
          changeButton={() => { this.setState({ segmentIndex: 1 }); }}
          logIndexes={() => { console.log('active button index', activeIndex); console.log('active tab index', this.state.tabbarIndex) }}
          title="Page1" active={activeIndex == 0} tabbar={tabbar} />,
        tab: <Tab key="page1" />
      },
      {
        content: <TabPage key="page2" logIndexes={() => { console.log('active button index', activeIndex); console.log('active tab index', this.state.tabbarIndex) }}
          title="Page2" active={activeIndex == 1} tabbar={tabbar} />,
        tab: <Tab key="page2" />
      },
      {
        content: <TabPage key="page3" logIndexes={() => { console.log('active button index', activeIndex); console.log('active tab index', this.state.tabbarIndex) }}
          title="Page3" active={activeIndex == 2} tabbar={tabbar} />,
        tab: <Tab key="page3" />
      }
    ];
  }

  renderToolbar() {
    return (
      <Toolbar>
        <div className="left"><BackButton>Back</BackButton></div>
        <div className="center">
          <Segment index={this.state.segmentIndex} onPostChange={(event) => this.setState({ segmentIndex: event.index })} tabbarId="tabbar" style={{ width: '280px' }}>
            <button>Page 1</button>
            <button>Page 2</button>
            <button>Page 3</button>
          </Segment>
        </div>
      </Toolbar>
    );
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)} >

        {/* Comment <Tabbar> out to test this one */}
        <Segment index={1} style={{ width: '280px', margin: '10px 20px' }}>
          <button>Label 1</button>
          <button>Label 2</button>
          <button>Label 3</button>
        </Segment>

        <Tabbar
          id="tabbar"
          index={this.state.tabbarIndex}
          onPostChange={(event) => {
            this.setState({ tabbarIndex: event.index });
            console.log('postchange event', event);
          }}
          renderTabs={this.renderTabs}
        />
      </Page>
    );
  }
}

// bindings/vue/examples/components/Segment.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">
        <v-ons-segment tabbar-id="tabbar" :index.sync="segmentIndex" @postchange="segmentIndex = $event.index" style="width: 280px">
          <button>Page 1</button>
          <button>Page 2</button>
          <button>Page 3</button>
        </v-ons-segment>
      </div>
    </v-ons-toolbar>

    <!-- Comment <v-ons-tabbar> out to test this one -->
    <v-ons-segment :index.sync="segment2Index" style="width: 280px; margin: 10px 20px;">
      <button>Label 1</button>
      <button>Label 2</button>
      <button>Label 3</button>
    </v-ons-segment>

    <v-ons-tabbar id="tabbar" :tabs="tabs" :index.sync="tabbarIndex" @postchange="tabbarIndex = $event.index; log('postchange event', $event)"></v-ons-tabbar>
  </v-ons-page>
</template>

<script>
  const homePage = {
    template: `
      <v-ons-page>
        <h2>Page1</h2>
        <v-ons-button @click="changeTab">Change tab via tabbar</v-ons-button>
        <v-ons-button @click="changeButton">Change tab via segment</v-ons-button>
        <v-ons-button @click="logIndexes">Log current button index</v-ons-button>
      </v-ons-page>
    `,
    props: ['changeTab', 'changeButton', 'logIndexes']
  };

  const tabPage = {
    template: `
      <v-ons-page>
        <h2>{{title}}</h2>
        <v-ons-button @click="logIndexes">Log current button index</v-ons-button>
      </v-ons-page>
    `,
    props: ['title', 'logIndexes']
  };

	export default {
    data() {
      return {
        segmentIndex: 0,
        segment2Index: 1,
        tabbarIndex: 0,
        tabs: [
          {
            page: homePage,
            props: {
              changeTab: this.changeTab,
              changeButton: this.changeButton,
              logIndexes: this.logIndexes
            }
          },
          {
            page: tabPage,
            props: {
              title: 'Page2',
              logIndexes: this.logIndexes
            }
          },
          {
            page: tabPage,
            props: {
              title: 'Page3',
              logIndexes: this.logIndexes
            }
          }
        ]
      };
    },
    methods: {
      log(...args) {
        console.log(...args)
      },
      changeTab() {
        this.tabbarIndex = 1
      },
      changeButton() {
        this.segmentIndex = 1
      },
      logIndexes() {
        console.log('active button index', this.segmentIndex);
        console.log('active tab index', this.tabbarIndex);
      }
    }
	};
</script>

<style>
</style>
