// bindings/react/demo/examples/Splitter.js
import React from 'react';

import {
  Splitter,
  SplitterSide,
  SplitterContent,
  Page,
  Toolbar,
  Button
} from 'react-onsenui';

import MyToolbar from './MyToolbar';

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showLeft: false,
      showRight: false,
      openLeft: false,
      openRight: false,
      isSwipeable: true
    };
  }

  handleLeftClose() {
    this.setState({
      openLeft: false
    });
  }

  handleLeftOpen() {
    this.setState({
      openLeft: true
    });
  }

  handleRightClose() {
    this.setState({
      openRight: false
    });
  }

  handleRightOpen() {
    this.setState({
      openRight: true,
    });
  }

  render() {
    return (
      <Page renderToolbar={() => <MyToolbar title="Splitter" />} >
        <Splitter>
          <SplitterSide
            side="left"
            width={200}
            collapse={!this.state.showLeft}
            isOpen={this.state.openLeft}
            onClose={this.handleLeftClose.bind(this)}
            onOpen={this.handleLeftOpen.bind(this)}
            isSwipeable={this.state.isSwipeable}>
            <Page>
              <Toolbar>
                <div className="center">content</div>
              </Toolbar>
            </Page>
          </SplitterSide>

          <SplitterContent>
            <Page renderToolbar={() => <MyToolbar title="ons-splitter-content" />}>
              <p>
                <Button
                  onClick={() => this.setState({isSwipeable: !this.state.isSwipeable})}
                >
                  {this.state.isSwipeable ? 'Disable Swipe' : 'Enable Swipeable'}
                </Button>
              </p>
              <p>
                <Button
                  onClick={() => this.setState({showLeft: !this.state.showLeft})}
                  >toggle left menu 2</Button>
              </p>
              <p>
                <Button
                  onClick={() => this.setState({showRight: !this.state.showRight })} > toggle right menu</Button> </p>

              <p>
                <Button
                  onClick={() => this.setState({openLeft: true})}>
                  Open left menu
                </Button>
              </p>

              <p>
                <Button
                  onClick={() => this.setState({openRight: true})}>
                  Open right menu
                </Button>
              </p>
            </Page>
          </SplitterContent>

          <SplitterSide
            side="right"
            width={300}
            collapse={!this.state.showRight}
            isOpen={this.state.openRight}
            onClose={this.handleRightClose.bind(this)}
            onOpen={this.handleRightOpen.bind(this)}
            isSwipeable={this.state.isSwipeable}>
            <Page>
              <Toolbar>
                <div className="center">ons-splitter-side</div>
              </Toolbar>
            </Page>
          </SplitterSide>
        </Splitter>
      </Page>
    );
  }
}

// bindings/vue/examples/components/Splitter.vue
<template>
  <ons-page>
    <ons-splitter>
      <ons-splitter-side
        :side="side"
        :collapse="collapse"
        :swipeable="swipeable"
        :width="width"
        :open="open"
        @preopen="open = true"
        @postclose="open = false"
      >
        <ons-page>
          <ons-list>
            <ons-list-item
              v-for="item in [1, 2, 3, 4]"
              @click="open = false"
              tappable>
              Menu item {{ item }}
            </ons-list-item>
          </ons-list>
        </ons-page>
      </ons-splitter-side>
      <ons-splitter-content>
        <ons-page>
          <ons-toolbar>
            <div class="left">
            </div>
            <div class="center">Side menu</div>
          </ons-toolbar>
          <p style="text-align: center">
            Swipe right to open menu!
          </p>

          <ons-list>
            <ons-list-item>
              <div class="center">
                Side
              </div>
              <div class="right">
                <select v-model="side">
                  <option>left</option>
                  <option>right</option>
                </select>
              </div>
            </ons-list-item>
            <ons-list-item>
              <div class="center">
                Swipeable
              </div>
              <div class="right">
                <ons-switch
                  :checked="swipeable"
                  @change="swipeable = $event.target.checked"
                >
                </ons-switch>
              </div>
            </ons-list-item>
            <ons-list-item>
              <div class="center">
                Collapse
              </div>
              <div class="right">
                <ons-switch
                  :checked="collapse"
                  @change="collapse = $event.target.checked"
                >
                </ons-switch>
              </div>
            </ons-list-item>
            <ons-list-item>
              <div class="center">
                Open
              </div>
              <div class="right">
                <ons-switch
                  :checked="open"
                  @change="open = $event.target.checked"
                >
                </ons-switch>
              </div>
            </ons-list-item>
          </ons-list>
        </ons-page>
      </ons-splitter-content>
    </ons-splitter>
  </ons-page>
</template>

<script>
  import {
    OnsSplitterSide,
    OnsSwitch
  } from 'vue-onsenui';

	export default {
    data: () => (
      {
        side: 'left',
        width: '200px',
        collapse: '',
        swipeable: true,
        open: false
      }
    ),

    components: {
      OnsSplitterSide,
      OnsSwitch
    }
	};
</script>
